-- 1. Enable Row Level Security (RLS) is good practice, but for this MVP we keep it open for public READ.
-- WRITE permissions will be restricted to the Service Role (Backend API) only.

-- TABLE: rounds
-- Stores historical data about each game round.
CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    status TEXT DEFAULT 'active', -- 'active', 'ended', 'processing_payout', 'completed'
    total_pot NUMERIC DEFAULT 0,
    winner_wallet TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLE: game_state
-- The "Singleton" table. We only strictly need ROW with ID=1.
CREATE TABLE IF NOT EXISTS game_state (
    id BIGINT PRIMARY KEY,
    current_round_id BIGINT REFERENCES rounds(id),
    timer_end TIMESTAMPTZ NOT NULL, -- The absolute timestamp when the game dies
    push_count BIGINT DEFAULT 0,
    treasury_balance NUMERIC DEFAULT 0,
    last_pushers JSONB DEFAULT '[]', -- Array of recent wallets for the UI
    is_paused BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLE: pushes
-- The raw ledger of valid pushes confirmed by Helius.
CREATE TABLE IF NOT EXISTS pushes (
    signature TEXT PRIMARY KEY, -- Solana Transaction Signature
    round_id BIGINT REFERENCES rounds(id),
    pusher_wallet TEXT NOT NULL,
    amount NUMERIC NOT NULL, -- Amount of SNOW
    token_mint TEXT, -- To verify it's the correct token
    block_time TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- POLICIES (Security)
-- Allow anyone (Anon) to READ game state (so the Frontend works without login)
ALTER TABLE game_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Game State" ON game_state FOR SELECT USING (true);

ALTER TABLE rounds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Rounds" ON rounds FOR SELECT USING (true);

ALTER TABLE pushes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Pushes" ON pushes FOR SELECT USING (true);

-- INITIAL SEED
-- We initialize the first round and the game state so the app doesn't crash.
DO $$
DECLARE
    first_round_id BIGINT;
BEGIN
    -- 1. Create the first round if it doesn't exist
    INSERT INTO rounds (status, total_pot)
    VALUES ('active', 0)
    RETURNING id INTO first_round_id;

    -- 2. Initialize Game State (ID=1)
    INSERT INTO game_state (id, current_round_id, timer_end, push_count, treasury_balance)
    VALUES (
        1, 
        first_round_id, 
        NOW() + INTERVAL '3 minutes', -- Start with 3 mins for testing
        0, 
        0
    )
    ON CONFLICT (id) DO NOTHING;
END $$;
